// Explicitly curated forms and relationships. Similar spelling alone is never
// treated as proof of a cognate or of equivalent grammar.
export const CONCEPTS = Object.freeze({
  speak: {
    id: "speak",
    gloss: "to speak or talk with someone",
    forms: {
      "pt-BR": "falar",
      "es-419": "hablar",
      "it-IT": "parlare",
      "fr-FR": "parler",
      "ht-HT": "pale",
      "ca-ES": "parlar",
      "sw-TZ": "kuzungumza",
    },
  },
  "future-plan": {
    id: "future-plan",
    gloss: "a planned future action",
    forms: {
      "pt-BR": "vou visitar",
      "es-419": "voy a visitar",
      "ht-HT": "mwen pral vizite",
    },
  },
  "polite-request": {
    id: "polite-request",
    gloss: "asking for something politely",
    forms: {
      "it-IT": "vorrei",
      "fr-FR": "je voudrais",
      "ht-HT": "mwen ta renmen",
      "ca-ES": "voldria",
    },
  },
  house: {
    id: "house",
    gloss: "a dwelling",
    forms: {
      "pt-BR": "casa",
      "es-419": "casa",
      "it-IT": "casa",
      "fr-FR": "maison",
      "ht-HT": "kay",
      "ca-ES": "casa",
      "sw-TZ": "nyumba",
    },
  },
  "weekend-invitation": {
    id: "weekend-invitation",
    gloss: "inviting someone to a weekend activity",
    forms: { "pt-BR": "Vamos à feira no domingo?" },
  },
  "past-narrative": {
    id: "past-narrative",
    gloss: "a completed event against past background",
    forms: { "es-419": "Llovía cuando salí de casa." },
  },
  "ask-directions": {
    id: "ask-directions",
    gloss: "asking for a place's location",
    forms: { "es-419": "¿Dónde está la biblioteca?" },
  },
  "article-preposition": {
    id: "article-preposition",
    gloss: "preposition combined with an article",
    forms: { "it-IT": "al mercato" },
  },
  "completed-event": {
    id: "completed-event",
    gloss: "a completed past event",
    forms: { "fr-FR": "j'ai visité" },
  },
  "daily-routine": {
    id: "daily-routine",
    gloss: "ordinary repeated activities",
    forms: { "ca-ES": "Cada matí em llevo..." },
  },
  "market-purchase": {
    id: "market-purchase",
    gloss: "asking for food and a quantity at a market",
    forms: { "ca-ES": "Voldria un quilo de pomes." },
  },
  "noun-agreement": {
    id: "noun-agreement",
    gloss: "an adjective agrees with its noun class",
    forms: { "sw-TZ": "kitabu kizuri / vitabu vizuri" },
  },
  "greeting-exchange": {
    id: "greeting-exchange",
    gloss: "greeting someone and exchanging wellbeing",
    forms: { "sw-TZ": "Hujambo? Sijambo, asante." },
  },
  "pregnancy-embarrassment": {
    id: "pregnancy-embarrassment",
    gloss: "contrast between a Spanish word for pregnant and a Portuguese word for embarrassed",
    forms: { "es-419": "embarazada", "pt-BR": "embaraçada" },
  },
});

export const RELATIONSHIPS = Object.freeze([
  {
    sourceLanguage: "pt-BR",
    targetLanguage: "es-419",
    conceptId: "speak",
    sourceForm: "falar",
    targetForm: "hablar",
    type: "cognate",
    note: "Related verbs with different modern spellings and pronunciation; do not substitute one form for the other.",
  },
  {
    sourceLanguage: "it-IT",
    targetLanguage: "fr-FR",
    conceptId: "speak",
    sourceForm: "parlare",
    targetForm: "parler",
    type: "cognate",
    note: "Related forms; French and Italian pronunciation and verb behavior still need separate practice.",
  },
  {
    sourceLanguage: "ca-ES",
    targetLanguage: "it-IT",
    conceptId: "speak",
    sourceForm: "parlar",
    targetForm: "parlare",
    type: "cognate",
    note: "Related forms in Catalan and Italian; spelling similarity does not make the full sentence interchangeable.",
  },
  {
    sourceLanguage: "fr-FR",
    targetLanguage: "ht-HT",
    conceptId: "speak",
    sourceForm: "parler",
    targetForm: "pale",
    type: "historical_lexical_relationship",
    note: "Kreyòl pale has a French lexical source; Haitian Creole grammar and orthography are independent.",
  },
  {
    sourceLanguage: "pt-BR",
    targetLanguage: "es-419",
    conceptId: "house",
    sourceForm: "casa",
    targetForm: "casa",
    type: "cognate",
    note: "The shared written form can aid meaning retrieval; pronunciation and surrounding grammar differ.",
  },
  {
    sourceLanguage: "es-419",
    targetLanguage: "pt-BR",
    conceptId: "future-plan",
    sourceForm: "voy a visitar",
    targetForm: "vou visitar",
    type: "grammatical",
    note: "Both express a plan, but Spanish uses a before the infinitive and Brazilian Portuguese normally does not.",
  },
  {
    sourceLanguage: "fr-FR",
    targetLanguage: "ht-HT",
    conceptId: "polite-request",
    sourceForm: "je voudrais",
    targetForm: "mwen ta renmen",
    type: "semantic",
    note: "Both can make a polite request; Kreyòl uses its own pronouns and tense-aspect patterns.",
  },
  {
    sourceLanguage: "sw-TZ",
    targetLanguage: "pt-BR",
    conceptId: "house",
    sourceForm: "nyumba",
    targetForm: "casa",
    type: "semantic",
    note: "The forms share a meaning here; no cognate or grammatical relationship is asserted.",
  },
  {
    sourceLanguage: "es-419",
    targetLanguage: "pt-BR",
    conceptId: "pregnancy-embarrassment",
    sourceForm: "embarazada",
    targetForm: "embaraçada",
    type: "false_friend",
    note: "Spanish embarazada means pregnant; Brazilian Portuguese embaraçada commonly means embarrassed or awkward.",
  },
]);
